[project]
name = "bam-pybis-workshop"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.3",
    "mkdocs-click>=0.9.0",
    "mkdocs-material>=9.7.1",
    "mkdocstrings>=1.0.2",
    "mkdocstrings-python>=2.0.1",
    "pybis~=1.37.1rc4",
]
